services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3001:3001" # Проброс порта 3001 контейнера на порт 3001 хоста
    volumes:
      - ./back/data:/app/data # Привязка папки для сохранения данных SQLite
    environment:
      NODE_ENV: production
    command: sh -c "npm run migrate:latest && npm start"
    restart: always

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        VITE_API_URL: /api
    ports:
      - "80:80" # Проброс порта 80 из контейнера на порт 80 хоста
    depends_on:
      - back # Зависимость от бэкенд-сервиса
    restart: always